### PR TITLE
Add TLS verification for clients

### PR DESCRIPTION
**Pull request by davidcurado**
I've implemented a small change into fsconsul to allow the use of TLS encryption and client-side verification.

### CODE REVIEW

**Comment by ryanbreen** [comment]
This looks really cool!

Could you add a test to watch_test.go?

**Comment by davidcurado** [comment]
Sorry for the late reply. Do you mind if I alter the travis file? I need to enable TLS on the consul agent to test it.

**Comment by ryanbreen** [comment]
Totally cool

**Comment by ryanbreen** [comment]
I went ahead and merged because this LGTM.  I'll publish a new binary once we get tests.

Thanks!

**Pull request merged**
