### PR TITLE
Testing for TLS

### PR DESCRIPTION
**Pull request by davidcurado**
The tests that are executed against consul connect both with TLS and without.

### CODE REVIEW

**Comment by ryanbreen** [comment]
I would prefer that you move the creation of the CACert into `watch_test.go`.  As it is, `go test` no longer works unless someone manually follows the steps from the travis config.

**Comment by davidcurado** [comment]
Wouldn't it be better, then, to keep a pre-generated key-pair for testing purposes in the git?

**Comment by ryanbreen** [comment]
Yep, that makes sense.

**Comment by ryanbreen** [comment]
Thanks!

**Pull request merged**
